backend:
  # for local development
  name: proxy
  proxy_url: "http://localhost:8081/api/v1"
  branch: master
  # # Use netlify identity as backend
  # name: git-gateway
  # branch: master
  # ### enable below lines for github integration ###
  # # name: github
  # # repo: surjithctly/neat-starter
media_folder: src/static/img
public_folder: /static/img

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

# publish_mode: editorial_workflow

collections:
  - label: Pages
    name: pages
    folder: src/pages
    create: true
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Nav Title (if not title), name: nav-title, widget: string, required: false }
      - { label: Nav Order, name: order, widget: number, value_type: int }
      - { label: Permalink, name: permalink, widget: string }
      - { label: Description, name: description, widget: string, required: false }
      - { label: Author, name: author, widget: string, required: false }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Header Image, name: header, widget: file, required: false }
      - { label: Body, name: body, widget: markdown }
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: Quick Links
        name: links
        file: src/_data/quicklinks.yaml
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: Site Settings
        name: settings
        file: src/_data/settings.yaml
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Logo, name: logo, widget: file }
